name: generate

on:
  push:
    branches:
      - main

jobs:
  generate-cv:
    name: generate-cv
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install weasyprint
        run: sudo apt install weasyprint

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install project dependencies
        run: uv sync

      - name: Generate outputs
        run: uv run python -m cv.generate

      - name: Upload via SSH
        run: ls ./dist
