name: generate

on:
  push:
    branches:
      - main

jobs:
  generate-cv:
    name: generate-cv
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install weasyprint
        run: sudo apt install weasyprint

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install project dependencies
        run: uv sync

      - name: Generate outputs
        run: uv run python -m cv.generate

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Add Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Sync Static Files
        run: |
          rsync -avz --delete -e "ssh -p ${{ secrets.SSH_PORT }}" \
          ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/website/cv
